name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install NumPy
      run: python -m pip install numpy

    - name: Install dependencies
      run: |
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
